{"name": "test_fail_example", "status": "failed", "statusDetails": {"message": "AssertionError: One is not two\nassert 1 == 2\n  +1\n  -2", "trace": "def test_fail_example():\n>       assert 1 == 2, 'One is not two'\nE       AssertionError: One is not two\nE       assert 1 == 2\nE         +1\nE         -2\n\ntests/test_healthcheck.py:21: AssertionError"}, "start": 1611089867581, "stop": 1611089867581, "uuid": "9b695309-d578-4b15-b051-a7b3ebfd207e", "historyId": "6ef27b40eebcb5c3f53a5781376e9b11", "testCaseId": "c9566442bc0748134da9d13132f894a1", "fullName": "tests.test_healthcheck#test_fail_example", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_healthcheck"}, {"name": "host", "value": "atlas"}, {"name": "thread", "value": "60814-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_healthcheck"}]}