{"name": "test_create_multiple_users", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 201\n  +400\n  -201", "trace": "@pytest.mark.multiple_data01\n    def test_create_multiple_users():\n        # API\n        file = open('/home/adi/Boast/boast_api_test/tests/data_driven_testing/create_multiple_users.json')\n        json_file = json.loads(file.read())\n    \n        obj = library.Common('/home/adi/Boast/boast_api_test/tests/data_driven_testing/multiple_users.xlsx', 'Sheet1')\n        col = obj.fetch_column_count()\n        row = obj.fetch_row_count()\n        key_list = obj.fetch_key_names()\n    \n        for i in range(2, row+1):\n            updated_json_request = obj.update_request_with_data(i, json_file, key_list)\n            response = requests.post('http://badger.boast.net:8080/api/users/user/', json=updated_json_request,\n                                     auth=credentials)\n>           assert response.status_code == 201\nE           assert 400 == 201\nE             +400\nE             -201\n\ntests/data_driven_testing/test_multiple_data.py:25: AssertionError"}, "attachments": [{"name": "log", "source": "5827d526-fee8-4dde-945e-e8209ae54327-attachment.txt", "type": "text/plain"}], "start": 1611090110439, "stop": 1611090110585, "uuid": "12d64f23-a831-490d-9929-0d3c7716d5f7", "historyId": "ef881f3b4b2ee67b3271794a642c7ffd", "testCaseId": "3ce904d8015119fdeae9b02ba6bac5a5", "fullName": "tests.data_driven_testing.test_multiple_data#test_create_multiple_users", "labels": [{"name": "tag", "value": "multiple_data01"}, {"name": "parentSuite", "value": "tests.data_driven_testing"}, {"name": "suite", "value": "test_multiple_data"}, {"name": "host", "value": "atlas"}, {"name": "thread", "value": "61659-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.data_driven_testing.test_multiple_data"}]}